-- =====================================================================
-- ShopEase E-Commerce QA Database Validation Script
-- =====================================================================
-- This script contains the database schema, sample data setups, and
-- exactly 25 SQL queries used for backend data integrity checks.
-- Compatible with SQLite, PostgreSQL, and MySQL databases.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Database Schema Definitions
-- ---------------------------------------------------------------------

CREATE TABLE users (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'Customer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    product_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL CHECK(price >= 0),
    stock INTEGER NOT NULL CHECK(stock >= 0),
    category VARCHAR(50),
    rating DECIMAL(3,2) DEFAULT 0.00
);

CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    total_amount DECIMAL(10,2) NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    order_status VARCHAR(20) DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE order_items (
    order_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER NOT NULL CHECK(quantity > 0),
    price_per_unit DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE cart_items (
    cart_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    product_id INTEGER,
    quantity INTEGER NOT NULL CHECK(quantity > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE,
    UNIQUE(user_id, product_id)
);

CREATE TABLE payments (
    payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER,
    payment_status VARCHAR(20) NOT NULL,
    payment_token VARCHAR(255) NOT NULL, -- Token generated by processor (never store CVV/PAN!)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- ---------------------------------------------------------------------
-- 2. Sample Data Insertion
-- ---------------------------------------------------------------------

INSERT INTO users (username, email, password_hash, role) VALUES 
('testuser1', 'testuser1@example.com', '$2b$12$Kj6mC5o...', 'Customer'),
('testuser2', 'testuser2@example.com', '$2b$12$Kj6mC5o...', 'Customer'),
('adminuser', 'admin@shopease.com', '$2b$12$Kj6mC5o...', 'Admin'),
('guest_user', 'guest@example.com', '$2b$12$Kj6mC5o...', 'Customer');

INSERT INTO products (title, description, price, stock, category, rating) VALUES 
('iPhone 15', 'Apple 128GB Smart Phone', 999.99, 15, 'Electronics', 4.8),
('iPad Pro', 'Apple 11 inch tablet', 799.99, 3, 'Electronics', 4.5),
('Wireless Mouse', 'Ergonomic rechargeable mouse', 25.50, 0, 'Electronics', 4.2),
('Leather Wallet', 'RFID blocking leather wallet', 45.00, 50, 'Apparel', 4.0),
('Keychron Keyboard', 'Mechanical gaming keyboard', 89.99, 8, 'Electronics', 4.7),
('Running Shoes', 'Breathable athletic sneakers', 120.00, 30, 'Apparel', 4.3);

INSERT INTO orders (user_id, total_amount, shipping_address, zip_code, order_status) VALUES 
(1, 1089.98, '123 Main St, New York, NY', '10001', 'Shipped'),
(1, 45.00, '123 Main St, New York, NY', '10001', 'Pending'),
(2, 799.99, '456 Oak Rd, San Francisco, CA', '94102', 'Delivered'),
(2, 210.00, '456 Oak Rd, San Francisco, CA', '94102', 'Pending');

INSERT INTO order_items (order_id, product_id, quantity, price_per_unit) VALUES 
(1, 1, 1, 999.99),
(1, 5, 1, 89.99),
(2, 4, 1, 45.00),
(3, 2, 1, 799.99),
(4, 6, 1, 120.00),
(4, 5, 1, 89.99); -- Price discrepancy: testing order item details matching base product price

INSERT INTO cart_items (user_id, product_id, quantity) VALUES 
(1, 2, 1),
(2, 1, 2);

INSERT INTO payments (order_id, payment_status, payment_token) VALUES 
(1, 'Success', 'tok_visa_1234567890'),
(2, 'Pending', 'tok_pending_98765432'),
(3, 'Success', 'tok_mastercard_44445555');

-- ---------------------------------------------------------------------
-- 3. 25 QA Validation Queries
-- ---------------------------------------------------------------------

-- Query 01: Verify registration username uniqueness constraint (should return 0 rows if unique works).
SELECT username, COUNT(*) 
FROM users 
GROUP BY username 
HAVING COUNT(*) > 1;

-- Query 02: Identify users holding the Admin role to audit privilege settings.
SELECT user_id, username, email 
FROM users 
WHERE role = 'Admin';

-- Query 03: Retrieve active users who registered in the last 24 hours.
SELECT username, email, created_at 
FROM users 
WHERE created_at >= DATETIME('now', '-1 day');

-- Query 04: Validate that password hashes are not empty and do not contain plaintext markers like "Pass".
SELECT user_id, username 
FROM users 
WHERE password_hash IS NULL OR password_hash LIKE 'Pass%';

-- Query 05: Verify there are no duplicate email registrations (case-insensitive audit).
SELECT LOWER(email), COUNT(*) 
FROM users 
GROUP BY LOWER(email) 
HAVING COUNT(*) > 1;

-- Query 06: List products that are completely out of stock.
SELECT product_id, title, category 
FROM products 
WHERE stock = 0;

-- Query 07: List products with stock level below the Low Inventory Warning threshold (5 units).
SELECT product_id, title, stock 
FROM products 
WHERE stock < 5 AND stock > 0;

-- Query 08: Validate data constraint: Check for products with negative prices or negative stock.
SELECT * 
FROM products 
WHERE price < 0.00 OR stock < 0;

-- Query 09: Find products with invalid/corrupted rating metadata (ratings must be between 0.0 and 5.0).
SELECT * 
FROM products 
WHERE rating < 0.0 OR rating > 5.0;

-- Query 10: Count total products available per category (Aggregate verification).
SELECT category, COUNT(*) AS product_count, SUM(stock) AS total_inventory 
FROM products 
GROUP BY category;

-- Query 11: Calculate the average price of products within the 'Electronics' category.
SELECT AVG(price) AS average_price 
FROM products 
WHERE category = 'Electronics';

-- Query 12: List the top 3 most expensive products (Boundary check for sorting).
SELECT product_id, title, price 
FROM products 
ORDER BY price DESC 
LIMIT 3;

-- Query 13: Join Query: Retrieve the shopping cart contents for user_id = 1.
SELECT c.cart_id, u.username, p.title, c.quantity, p.price, (c.quantity * p.price) AS subtotal
FROM cart_items c
JOIN users u ON c.user_id = u.user_id
JOIN products p ON c.product_id = p.product_id
WHERE c.user_id = 1;

-- Query 14: Join Query: Fetch detailed order summary invoice matching Order ID = 1.
SELECT o.order_id, u.username, p.title, oi.quantity, oi.price_per_unit, (oi.quantity * oi.price_per_unit) AS line_subtotal
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN users u ON o.user_id = u.user_id
JOIN products p ON oi.product_id = p.product_id
WHERE o.order_id = 1;

-- Query 15: Data Integrity Check: Identify orders where the total_amount does not match the sum of order items.
SELECT o.order_id, o.total_amount, SUM(oi.quantity * oi.price_per_unit) AS items_sum
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.order_id, o.total_amount
HAVING ABS(o.total_amount - SUM(oi.quantity * oi.price_per_unit)) > 0.01;

-- Query 16: Audit: Identify products whose unit price in order_items differs from the current product catalog price.
SELECT oi.order_id, p.product_id, p.title, oi.price_per_unit AS order_item_price, p.price AS current_catalog_price
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
WHERE oi.price_per_unit <> p.price;

-- Query 17: Find users who have placed more than 1 order (Purchase frequency check).
SELECT u.user_id, u.username, COUNT(o.order_id) AS total_orders
FROM users u
JOIN orders o ON u.user_id = o.user_id
GROUP BY u.user_id, u.username
HAVING COUNT(o.order_id) > 1;

-- Query 18: Audit: Retrieve orders that were processed without matching entry in payments table.
SELECT o.order_id, o.created_at, o.total_amount
FROM orders o
LEFT JOIN payments p ON o.order_id = p.order_id
WHERE p.payment_id IS NULL;

-- Query 19: Find order items where the quantity ordered exceeds current available warehouse stock.
SELECT oi.order_id, p.title, oi.quantity AS quantity_ordered, p.stock AS current_warehouse_stock
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
WHERE oi.quantity > p.stock;

-- Query 20: Aggregate: Calculate total revenue earned from successfully processed credit card payments.
SELECT SUM(o.total_amount) AS total_revenue
FROM orders o
JOIN payments p ON o.order_id = p.order_id
WHERE p.payment_status = 'Success';

-- Query 21: Find users who have items in their cart but have not placed any orders yet (Abandoned checkout audit).
SELECT DISTINCT u.user_id, u.username, u.email
FROM users u
JOIN cart_items c ON u.user_id = c.user_id
LEFT JOIN orders o ON u.user_id = o.user_id
WHERE o.order_id IS NULL;

-- Query 22: Integrity Audit: Identify orphaned records in order_items table lacking a matching parent order record.
SELECT oi.order_item_id, oi.order_id
FROM order_items oi
LEFT JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_id IS NULL;

-- Query 23: Count order frequencies grouped by Status (Pending, Shipped, Delivered) to audit state updates.
SELECT order_status, COUNT(*) AS order_count
FROM orders
GROUP BY order_status;

-- Query 24: Security Audit: Verify that no payment gateway details containing cleartext card patterns exist.
SELECT payment_id, order_id, payment_token
FROM payments
WHERE payment_token LIKE '%4111%' OR payment_token LIKE '%visa%' OR length(payment_token) < 5;

-- Query 25: Identify the user who spent the most amount of money on the platform (VIP customer metrics).
SELECT u.user_id, u.username, SUM(o.total_amount) AS total_spent
FROM users u
JOIN orders o ON u.user_id = o.user_id
JOIN payments p ON o.order_id = p.order_id
WHERE p.payment_status = 'Success'
GROUP BY u.user_id, u.username
ORDER BY total_spent DESC
LIMIT 1;
